### ISSUE TITLE
Not all parameters passed to action

### ISSUE THREAD

**Issue by genebean** [stefanprodan/kube-tools#14]
When I have my action file set to `uses: stefanprodan/kube-tools@v1.0.0` it seems only 4 of the 5 inputs are passed in. Switching to `uses: stefanprodan/kube-tools@master` fixes this. Not sure why this is the case.

**Comment by stefanprodan** [comment]
Fixed in `stefanprodan/kube-tools@v1.5.0` and `stefanprodan/kube-tools@v1`
