### ISSUE TITLE
Forward v1 branch to pick up 1.6.0 release

### ISSUE THREAD

**Issue by Iristyle** [stefanprodan/kube-tools#46]
The current head of the https://github.com/stefanprodan/kube-tools/tree/v1 branch is pointing to the v1.5.0 release, rather than the v1.6.0 release and should be fast forwarded

**Comment by stefanprodan** [comment]
Fixed here: https://github.com/stefanprodan/kube-tools/blob/v1/action.yml

**Comment by Iristyle** [comment]
Thanks!
