### ISSUE TITLE
Provide KUBECONFIG

### ISSUE THREAD

**Issue by riker09** [stefanprodan/kube-tools#6]
I want to use this action to deploy with `helmv3`. I have created a GitHub Secret with the contents of a my `./kubeconfig`. Currently I have to paste the content of that secret into a file and then export it back to `KUBECONFIG`.

Is there a better way of doing this? Maybe I'm missing something obvious?

**Comment by riker09** [comment]
I just dug around a little bit. Even DeliveryBot does it like this, even though they are better at hiding his:

https://github.com/deliverybot/helm/blob/9013bbf586d8af9a4f36e7f99271c6f2533a7648/index.js#L216

**Comment by stefanprodan** [comment]
I think kube-tools could do the same but I expect for kubeconfig to be generated by some action that runs before it. For example: kind, gke, eks, aks all of these are creating the kubeconfig.

**Comment by riker09** [comment]
I'm pretty much a bloody beginner regarding Kubernetes and Helm, and CI/CD with GitHub Actions for that matter. So for now I will generate the KUBECONFIG in a step before using any Helm action.
